services:
  - type: web
    name: votacao-api
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: votacao-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: votacao-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: votacao-db
          property: password
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
databases:
  - name: votacao-db
    plan: free